# permissions for end users to edit judgeservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cloud-judge
    app.kubernetes.io/managed-by: kustomize
  name: judgeserver-editor-role
rules:
- apiGroups:
  - judge.wecoding.top
  resources:
  - judgeservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - judge.wecoding.top
  resources:
  - judgeservers/status
  verbs:
  - get
