---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - judge.wecoding.top
  resources:
  - judgeservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - judge.wecoding.top
  resources:
  - judgeservers/finalizers
  verbs:
  - update
- apiGroups:
  - judge.wecoding.top
  resources:
  - judgeservers/status
  verbs:
  - get
  - patch
  - update
